name: CloseDrawer

task_name: CloseDrawer
lazy_eval: false

shape_meta: &shape_meta
  obs:
    robot0_agentview_left_image:
      shape: [128, 128, 3]
      type: rgb
    robot0_agentview_right_image:
      shape: [128, 128, 3]
      type: rgb
    robot0_eye_in_hand_image:
      shape: [128, 128, 3]
      type: rgb
    robot0_eef_pos:
      shape: [3]
      type: state
    robot0_eef_quat:
      shape: [4]
      type: state
    robot0_gripper_qpos:
      shape: [2]
      type: state
    robot0_base_pos:
      shape: [3]
      type: state
    robot0_base_quat:
      shape: [4]
      type: state
  action:
    shape: [12]


env_runner:
  _target_: oat.env_runner.robocasa_runner.RoboCasaRunner
  env_name: CloseDrawer
  robots: PandaOmron
  n_test: 50
  n_test_vis: 5
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 20
  n_parallel_envs: 10
  image_size: 128
  camera_names:
    - robot0_agentview_left
    - robot0_agentview_right
    - robot0_eye_in_hand
  state_ports:
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot0_base_pos
    - robot0_base_quat
  max_episode_steps: 500


dataset:
  _target_: oat.dataset.zarr_dataset.ZarrDataset
  zarr_path: data/robocasa/CloseDrawer_N${training.num_demo}.zarr
  obs_keys:
    - robot0_agentview_left_image
    - robot0_agentview_right_image
    - robot0_eye_in_hand_image
    - robot0_eef_pos
    - robot0_eef_quat
    - robot0_gripper_qpos
    - robot0_base_pos
    - robot0_base_quat
  action_key: action
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${horizon}
  seed: ${seed}
  val_ratio: 0.1
